name: ggtdd_frontend
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  provider: ^6.0.0
  http: ^1.2.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/ggtdd.png
    - assets/images/Ellipse_43.jpg
    - assets/images/Ellipse_44.png
    - assets/images/Ellipse_45.png

  #
