import 'package:flutter/material.dart';

class DefaultTags {
  static final List<Map<String, dynamic>> defaultTags = [
    {
      'default_tag_id': 1,
      'tag_name': '한밤',
      'type': 'time',
      'category': 'time_unit',
      'time_range': '00:00~03:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 2,
      'tag_name': '새벽',
      'type': 'time',
      'category': 'time_unit',
      'time_range': '03:00~06:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 3,
      'tag_name': '아침',
      'type': 'time',
      'category': 'time_unit',
      'time_range': '06:00~09:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 4,
      'tag_name': '늦은 오전',
      'type': 'time',
      'category': 'time_unit',
      'time_range': '09:00~12:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 5,
      'tag_name': '이른 오후',
      'type': 'time',
      'category': 'time_unit',
      'time_range': '12:00~15:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 6,
      'tag_name': '늦은 오후',
      'type': 'time',
      'category': 'time_unit',
      'time_range': '15:00~18:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 7,
      'tag_name': '저녁',
      'type': 'time',
      'category': 'time_unit',
      'time_range': '18:00~21:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 8,
      'tag_name': '늦은 밤',
      'type': 'time',
      'category': 'time_unit',
      'time_range': '21:00~24:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 9,
      'tag_name': '조식',
      'type': 'time',
      'category': 'meal_unit',
      'time_range': '06:00~08:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 10,
      'tag_name': '중식',
      'type': 'time',
      'category': 'meal_unit',
      'time_range': '12:00~14:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 11,
      'tag_name': '석식',
      'type': 'time',
      'category': 'meal_unit',
      'time_range': '18:00~20:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 12,
      'tag_name': '야식',
      'type': 'time',
      'category': 'meal_unit',
      'time_range': '22:00~04:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 13,
      'tag_name': '평일',
      'type': 'time',
      'category': 'week_unit',
      'time_range': '월~금',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 14,
      'tag_name': '주말',
      'type': 'time',
      'category': 'week_unit',
      'time_range': '토~일',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 15,
      'tag_name': '매일',
      'type': 'time',
      'category': 'week_unit',
      'time_range': '월~일',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 16,
      'tag_name': '격일 (월, 수, 금)',
      'type': 'time',
      'category': 'week_unit',
      'time_range': '월, 수, 금',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 17,
      'tag_name': '격일 (화, 목, 토)',
      'type': 'time',
      'category': 'week_unit',
      'time_range': '화, 목, 토',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 18,
      'tag_name': '주간',
      'type': 'time',
      'category': 'day_night_unit',
      'time_range': '06:00~18:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 19,
      'tag_name': '야간',
      'type': 'time',
      'category': 'day_night_unit',
      'time_range': '18:00~06:00',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 20,
      'tag_name': '출근',
      'type': 'time',
      'category': 'commute_unit',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 21,
      'tag_name': '등교',
      'type': 'time',
      'category': 'commute_unit',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 22,
      'tag_name': '퇴근',
      'type': 'time',
      'category': 'commute_unit',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 23,
      'tag_name': '하교',
      'type': 'time',
      'category': 'commute_unit',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 24,
      'tag_name': '집',
      'type': 'space',
      'category': 'place',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 25,
      'tag_name': '직장',
      'type': 'space',
      'category': 'place',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 26,
      'tag_name': '학교',
      'type': 'space',
      'category': 'place',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 27,
      'tag_name': '사업체',
      'type': 'space',
      'category': 'place',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 28,
      'tag_name': '휴게실',
      'type': 'space',
      'category': 'place',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 29,
      'tag_name': '식당',
      'type': 'space',
      'category': 'place',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 30,
      'tag_name': '헬스장',
      'type': 'space',
      'category': 'place',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 31,
      'tag_name': '기타 장소',
      'type': 'space',
      'category': 'place',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 32,
      'tag_name': '대중교통',
      'type': 'space',
      'category': 'vehicle',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 33,
      'tag_name': '자차',
      'type': 'space',
      'category': 'vehicle',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 34,
      'tag_name': '도보',
      'type': 'space',
      'category': 'vehicle',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 35,
      'tag_name': '재택 근무',
      'type': 'etc',
      'category': 'basic',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 36,
      'tag_name': '외출',
      'type': 'etc',
      'category': 'basic',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 37,
      'tag_name': '약속',
      'type': 'etc',
      'category': 'basic',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 38,
      'tag_name': '자기계발',
      'type': 'etc',
      'category': 'basic',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 39,
      'tag_name': '개인 업무',
      'type': 'etc',
      'category': 'basic',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 40,
      'tag_name': '집안일',
      'type': 'etc',
      'category': 'basic',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 41,
      'tag_name': '취미',
      'type': 'etc',
      'category': 'basic',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 42,
      'tag_name': '휴식',
      'type': 'etc',
      'category': 'basic',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 43,
      'tag_name': '가족/사회',
      'type': 'etc',
      'category': 'basic',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 44,
      'tag_name': '운동',
      'type': 'etc',
      'category': 'basic',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
    {
      'default_tag_id': 45,
      'tag_name': '식사',
      'type': 'etc',
      'category': 'basic',
      'time_range': null,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': null,
    },
  ];
}
